routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('dashboard');

Route::group(['middleware' => 'auth'], function () {

    Route::get('tasks/datatable', 'TaskController@datatable')->name('tasks.datatable');
    Route::get('tasks/{task}/done', 'TaskController@setAsDone')->name('tasks.done');
    Route::resource('tasks', 'TaskController');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Entities\Task;
use App\Http\Requests\DestroyTask;
use App\Http\Requests\StoreTask;
use Doctrine\ORM\EntityManagerInterface;
use Illuminate\Http\Request;
use Yajra\Datatables\Facades\Datatables;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('task.index');
    }

    /**
     * Process datatables ajax request.
     * @return \Illuminate\Http\JsonResponse
     */
    public function datatable() {

        $user = \Auth::user();

        $tasks = $user->getTasks();

        $serializer = \JMS\Serializer\SerializerBuilder::create()->build();
        $tasks = json_decode($serializer->serialize($tasks, 'json'), true);

        $datatable = Datatables::of($tasks)
            ->editColumn('date', function($row) {
                $date = new \DateTime($row['date']);
                return $date->format('Y-m-d');
            })
            ->editColumn('is_done', function($row){
                return $row['is_done'] ? 'Yes' : 'No';
            })
            ->addColumn('actions', 'crud_actions')
            ->rawColumns(['actions'])
            ->make(true);

        return $datatable;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('task.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\StoreTask  $request
     * @param \Doctrine\ORM\EntityManagerInterface $em
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTask $request, EntityManagerInterface $em)
    {
        $task = new Task(
            $request->get('name'),
            $request->get('description'),
            new \DateTime($request->get('date'))
        );

        if( !is_null($request->get('is_done')) ) {
            $task->setIsDone(true);
        } else {
            $task->setIsDone(false);
        }

        $task->setUser(\Auth::user());

        $em->persist($task);
        $em->flush();

        return redirect( route('tasks.index') )->with('success', 'Task created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @param \Doctrine\ORM\EntityManagerInterface $em
     * @return \Illuminate\Http\Response
     */
    public function show($id, EntityManagerInterface $em)
    {
        $task = $em->getRepository(Task::class)->find($id);
        if(is_null($task))
            abort(404);

        return view('task.show', ['task' => $task]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @param \Doctrine\ORM\EntityManagerInterface $em
     * @return \Illuminate\Http\Response
     */
    public function edit($id, EntityManagerInterface $em)
    {
        $task = $em->getRepository(Task::class)->find($id);
        if(is_null($task))
            abort(404);

        return view('task.edit', ['task' => $task]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StoreTask  $request
     * @param  int  $id
     * @param \Doctrine\ORM\EntityManagerInterface $em
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTask $request, $id, EntityManagerInterface $em)
    {
        $task = $em->getRepository(Task::class)->find($id);

        $task->setName( $request->get('name') );
        $task->setDescription( $request->get('description') );
        $task->setDate( new \DateTime($request->get('date')) );

        if( !is_null($request->get('is_done')) ) {
            $task->setIsDone(true);
        } else {
            $task->setIsDone(false);
        }
        $em->persist($task);
        $em->flush();

        return redirect( route('tasks.edit', ['task' => $task->getId()]) )->with('success', 'Task updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @param \Doctrine\ORM\EntityManagerInterface $em
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, EntityManagerInterface $em)
    {
        $task = $em->getRepository(Task::class)->find($id);
        if(is_null($task))
            abort(404);

        $em->remove($task);
        $em->flush();

        return redirect( route('tasks.index') )->with('success', 'Task deleted!');
    }

    /**
     * Set task status as Done
     *
     * @param  int  $id
     * @param \Doctrine\ORM\EntityManagerInterface $em
     * @return \Illuminate\Http\Response
     */
    public function setAsDone($id, EntityManagerInterface $em)
    {
        $task = $em->getRepository(Task::class)->find($id);
        if(is_null($task))
            abort(404);

        $task->setIsDone(true);
        $em->persist($task);
        $em->flush();

        return redirect( route('tasks.index') )->with('success', 'Status changed as done for '.$task->getName());
    }
}

resources/views/crud_actions.blade.php
<div class="crud-actions">
    <a href="{{route('tasks.show', ['task' => $id])}}" class="btn btn-warning" title="show">
        <span class="glyphicon glyphicon-zoom-in"></span>
    </a>
    <a href="{{route('tasks.edit', ['task' => $id])}}" class="btn btn-primary" title="edit">
        <span class="glyphicon glyphicon-edit"></span>
    </a>
    <form class="destroyItem" action="{{route('tasks.destroy', ['task' => $id])}}" method="POST">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
        <button type="submit"class="btn btn-danger" title="destroy">
            <span class="glyphicon glyphicon-trash"></span>
        </button>
    </form>
    @if(!$is_done)
    <a href="{{route('tasks.done', ['task' => $id])}}" class="btn btn-success" title="done">
        <span class="glyphicon glyphicon glyphicon-ok"></span>
    </a>
    @endif
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">Navigation</div>

                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li role="presentation" @if(\Route::currentRouteName() == 'dashboard') class="active" @endif><a href="{{ route('dashboard') }}">DashBoard</a></li>
                        <li role="presentation" @if(preg_match('/^tasks./', \Route::currentRouteName())) class="active" @endif><a href="{{ route('tasks.index') }}">Tasks</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">@section('page_header') Dashboard @show</div>

                <div class="panel-body">

                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    @section('page_body')
                        You are logged in!
                    @show
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/plugins.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>

    @stack('scripts_header')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->getName() }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    @stack('scripts_footer')
</body>
</html>

resources/views/task/create.blade.php
@extends('home')

@section('page_header') Add task @endsection

@section('page_body')

    <div class="form-wrapper clearboth">
        @include('task.parts.form', ['action_url' => route('tasks.store')])
    </div>


@endsection

resources/views/task/edit.blade.php
@extends('home')

@section('page_header') Edit task @endsection

@section('page_body')

    <div class="form-wrapper clearboth">
        @include('task.parts.form', ['action_url' => route('tasks.update', ['task' => $task->getId()])])
    </div>


@endsection

resources/views/task/index.blade.php
@extends('home')

@section('page_header') Tasks List @endsection

@section('page_body')
    <div class="action-buttons pull-right">
        <a href="{{route('tasks.create')}}" class="btn btn-primary">Add</a>
    </div>

    <table class="table table-bordered" id="tasks-table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Done</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
        </thead>
    </table>

@endsection

@push('scripts_footer')
    <script>
        $(document).ready(function(){
            $(function() {
                $('#tasks-table').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: '{!! route('tasks.datatable') !!}',
                    "order": [],
                    columns: [
                        { data: 'id', name: 'id' },
                        { data: 'name', name: 'name' },
                        { data: 'description', name: 'description' },
                        { data: 'is_done', name: 'is_done' },
                        { data: 'date', name: 'date' },
                        { data: 'actions', name: 'actions' }
                    ]
                });
            });
        });
    </script>
@endpush

resources/views/task/parts/form.blade.php
@if(isset($errors) && $errors->count() > 0)
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
            <li>{{$error}}</li>
        @endforeach
    </ul>
</div>
@endif
<form action="{{$action_url}}" method="POST">
    {{ csrf_field() }}
    @if(isset($task))
        {{ method_field('PUT') }}
    @endif
    <div class="form-group">
        <label for="inputName">Name <span class="required">*</span></label>
        <input type="text" class="form-control" value="@if(isset($task)) {{ $task->getName() }} @endif" name="name" id="inputName" placeholder="Name">
    </div>
    <div class="form-group">
        <label for="inputDescription">Description <span class="required">*</span></label>
        <textarea class="form-control" name="description" id="inputDescription" placeholder="Description">@if(isset($task)){{ $task->getDescription() }}@endif</textarea>
    </div>
    <div class="form-group">
        <label for="inputDate">Date</label>
        <input type="text" class="form-control datepicker" value="@if(isset($task)){{ $task->getDate() }}@else{{ date('Y-m-d') }}@endif" id="inputDate" placeholder="Date" name="date">
    </div>
    <div class="checkbox">
        <label>
            <input name="is_done" @if(isset($task) && $task->getIsDone() === true) checked @endif type="checkbox"> Is done?
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{{route('tasks.index')}}" class="btn btn-danger">Cancel</a>
</form>

resources/views/task/show.blade.php
@extends('home')

@section('page_header') Show task @endsection

@section('page_body')

    <div class="task-details">
        <ul>
            <li><strong>ID:</strong> {{$task->getId()}}</li>
            <li><strong>Name:</strong> {{$task->getName()}}</li>
            <li><strong>Description:</strong> {{$task->getDescription()}}</li>
            <li><strong>Done:</strong> {{$task->showStatus()}}</li>
            <li><strong>Date:</strong> {{$task->getDate()}}</li>
        </ul>
        <a href="{{route('tasks.index')}}" class="btn btn-danger">Back</a>
    </div>

@endsection